
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/PolarGeospatialCenter/inventory"

[[constraint]]
  branch = "master"
  name = "github.com/azenk/iputils"

[[constraint]]
  name = "github.com/go-test/deep"
  version = "1.0.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.0.6"

[[constraint]]
  name = "github.com/sergi/go-diff"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "gopkg.in/go-playground/webhooks.v3"
  version = "3.10.0"

[[constraint]]
  name = "gopkg.in/src-d/go-billy.v3"
  version = "3.1.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.2.1"
